version: '3'

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_media: {}
  production_static: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: yatla_production_django
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start
    volumes:
      - production_media:/data/media
      - production_static:/data/static

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: yatla_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres

  nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    depends_on:
      - django
    env_file:
      - ./.envs/.production/.nginx
    networks:
      traefik:
        aliases:
          - yatla_nginx
      default:
        aliases:
          - nginx
    ports:
      - "80"
    labels:
      - traefik.enable=true
      - traefik.backend=yatla_nginx
      - traefik.frontend.rule=Host:yatla.mgabarda.com
      - traefik.docker.network=traefik
      - traefik.port=80
      - traefik.protocol=http
    volumes:
      - production_media:/data/media
      - production_static:/data/static

  redis:
    image: redis:3.2

networks:
  traefik:
    external: true
