version: '3'

volumes:
  staging_postgres_data: {}
  staging_postgres_backup: {}
  staging_caddy: {}
  staging_media: {}
  staging_static: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/staging/django/Dockerfile
    image: yatla_staging_django
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.staging/.django
      - ./.envs/.staging/.postgres
    command: /start
    volumes:
      - staging_media:/data/media
      - staging_static:/data/static

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: yatla_staging_postgres
    volumes:
      - staging_postgres_data:/var/lib/postgresql/data
      - staging_postgres_backup:/backups
    env_file:
      - ./.envs/.staging/.postgres

  nginx:
    build:
      context: .
      dockerfile: ./compose/staging/nginx/Dockerfile
    depends_on:
      - django
    env_file:
      - ./.envs/.staging/.nginx
    networks:
      - nginxproxy_net1
      - default
    ports:
      - "0.0.0.0:8014:80"
    volumes:
      - staging_media:/data/media
      - staging_static:/data/static

  redis:
    image: redis:3.2

networks:
  nginxproxy_net1:
    external:
      name: nginxproxy_net1
