# Generated by Django 2.1.6 on 2019-02-11 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("twits", "0001_initial")]

    operations = [
        migrations.AlterModelOptions(name="twit", options={"ordering": ["-created"]})
    ]
